INCLUDES+=-I/Users/Ninja/mediaone/mediaone/xbmc/cores/VideoPlayer

SRCS  = DVDCodecUtils.cpp
SRCS += DVDFactoryCodec.cpp

LIB=	DVDCodecs.a

include /Users/Ninja/mediaone/mediaone/Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))

