SRCS  = AddonButtonMap.cpp
SRCS += AddonButtonMapping.cpp
SRCS += AddonInputHandling.cpp
SRCS += PeripheralAddon.cpp
SRCS += PeripheralAddonTranslator.cpp

LIB = peripheral-addons.a

include /Users/Ninja/mediaone/mediaone/Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))
